import { useEffect, useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'

import ThreeIdResolver from '@ceramicnetwork/3id-did-resolver'
import Ceramic from '@ceramicnetwork/http-client'
import { DID } from 'dids'
import { fcl, getProvider, signMessage, verifySignatures } from '../utils/did-provider'
import { makeTile, getRewardSchema } from '../utils/ceramic'
import DocView from '../components/DocView'
import Button from '../components/Button'

const CERAMIC_URL = process.env.NEXT_PUBLIC_CERAMIC_API || 'http://localhost:7007'

export default function Home() {
  const [status, setStatus] = useState('Not authenticated');
  const [id, setId] = useState(0);

  const refresh = () => {
    window.ceramic = new Ceramic(CERAMIC_URL)
    let ceramic = window.ceramic;

    console.log('Ceramic:', ceramic)

    const resolver = {
      ...ThreeIdResolver.getResolver(ceramic),
    }
    const did = new DID({ resolver })

    ceramic.did = did;
    setStatus(ceramic.did.authenticated ? "Authenticated" : "Not authenticated")
    setId(0);
  }

  useEffect(async () => {
    if (!window.ceramic) {
      refresh()
    }
  }, [])

  const [doc, setDoc] = useState(null);
  const loadDoc = async (streamId) => {
    let ceramic = window.ceramic;

    setStatus('Loading ' + JSON.stringify(streamId))
    let c = await ceramic.loadStream(streamId);
    setDoc(c);
  }
  const updateDoc = async () => {
    await doc.update({ title: 'The great gatsby', message: 'something else' })
    console.log(doc.content)
    setDoc(doc)
    setcontent(doc ? JSON.stringify(doc.content) : "")
  }

  const [streamId, setStreamId] = useState('');
  const [content, setcontent] = useState('');
  useEffect(() => {
    setStreamId(doc ? doc.id.toString() : "")
    setcontent(doc ? JSON.stringify(doc.content) : "")
  }, [doc])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto max-w-xl mt-48">
        {status}
        {id ? <p>ID: {id}</p> : null}

        <DocView streamId={streamId} setStreamId={setStreamId} content={content} onLoad={loadDoc} updateDoc={updateDoc} />

        <Button onClick={async () => {
          refresh();
        }}>Get a new DID</Button>

        <Button onClick={async () => {
          console.log('Signed message:', await signMessage('hello'))
        }}>Sign a message</Button>

        <Button onClick={async () => {
          let ceramic = window.ceramic;

          const foo = await ceramic.did.resolve('did:3:kjzl6cwe1jw146hbs4gvmwftw7w5hwv1dfj2m2uwz0iyx0z0uruvu6bt7cw7xwh')
          console.log(foo);
        }}>Resolve sample DID</Button>

        <Button onClick={async () => {
          let ceramic = window.ceramic;

          const schema = await getRewardSchema(ceramic);
          const doc = await makeTile(ceramic, schema);
          console.log('Made a new doc!', doc.id.toString());
          setDoc(doc);
          window.doc = doc;
        }}>make doc</Button>


        <Button onClick={async () => {
          let ceramic = window.ceramic;

          if (!ceramic.did.authenticated) {
            setStatus('Sign in with Flow')
            const signedMessage = await signMessage('hello world')
            const trues = await verifySignatures('hello world', signedMessage);

            setStatus('Communicating with Ceramic network')
            try {
              const provider = await getProvider(ceramic, signedMessage);
              ceramic.did.setProvider(provider)
            } catch {
              console.error(ceramic.did)
            }
          }

          setStatus('Authenticating...')
          await ceramic.did.authenticate();
          setStatus('Authenticated')
          setId(ceramic.did.id);

        }}>Authenticate with Flow</Button>


        <Button onClick={async () => {
          await fcl.authenticate()
          const currentUser = await fcl.currentUser().snapshot()
          console.log('Current user', currentUser)
        }}>Get current user (fcl)</Button>
      </main>

    </div>
  )
}
